### ISSUE TITLE
How to add funds to proxy address?

### ISSUE THREAD

**Issue by v0d1ch** [obsidiansystems/hydra-pay#2]
Howdy :wave: 

Nice work on the `HydraPay` guys! 

I wanted to play a bit and I could run the demo out of the box which is great. 

A question I have is **how to fund proxy addresses**? 

You mention in the readme:

> Get a CIP-30 compatible CBOR transaction that will fund your Proxy Address.

but it would be really useful to document the process so that users can initialize the head and do all of the provided operations.

Suggestion:

 - I think it would be useful for people exploring `HydraPay` to be able to connect to the local devnet you spin. I didn't find any instructions on how to do that.
 

Looking forward to playing with `HydraPay` further!

**Comment by Yasuke** [comment]
@v0d1ch Glad you were able to run the demo without issue. The docs are definitely missing some things pending our first official release!

To answer your direct question you can get a transaction by doing the following request, (remember to tag this as per the README):

`"{"contents":["Funds","<cardano-address>",100000000],"tag":"GetAddTx"}"`
You can use Fuel instead of Funds to get a transaction for providing fuel.

**Comment by Yasuke** [comment]
The docs have been updated to include the updated API
